version: "2"

services:

  influxdb:
    extends:
      file: common.yml
      service: influxdb

  grafana:
    extends:
      file: common.yml
      service: grafana
    depends_on:
      - influxdb

  speedy:
    build:
      context: ./docker/speedy
      dockerfile: Dockerfile
    env_file:
      - ./configuration.env
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - ./docker/speedy/.npm/_logs:/home/.npm/_logs
    depends_on:
      - influxdb


volumes:
  influxdb_data: {}
  grafana_data: {}
